name: Fix PHP code style issues

on:
  push:
    paths:
      - 'src/laravel/**.php'

permissions:
  contents: write

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: cs-fixer
          coverage: none

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --config=.php-cs-fixer.dist.php --allow-risky=yes --diff

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling
